"""empty message

Revision ID: 47d95de15dfe
Revises: 
Create Date: 2022-04-11 23:30:56.170024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d95de15dfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['homeworld'], ['Planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favorite Planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Planets_Relation_id', sa.Integer(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Planets_Relation_id'], ['Planets.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favorite Characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Characters_Relation_id', sa.Integer(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Characters_Relation_id'], ['Characters.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['Characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favorite Starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Starships_Relation_id', sa.Integer(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Starships_Relation_id'], ['Starships.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Characters_id', sa.Integer(), nullable=True),
    sa.Column('Starships_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Characters_id'], ['Characters.id'], ),
    sa.ForeignKeyConstraint(['Starships_id'], ['Starships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pilots')
    op.drop_table('Favorite Starships')
    op.drop_table('Starships')
    op.drop_table('Favorite Characters')
    op.drop_table('Favorite Planets')
    op.drop_table('Characters')
    op.drop_table('User')
    op.drop_table('Planets')
    # ### end Alembic commands ###
