"""empty message

Revision ID: d96c121230f9
Revises: 47d95de15dfe
Create Date: 2022-04-12 00:19:09.969713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96c121230f9'
down_revision = '47d95de15dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Characters_ibfk_1', 'Characters', type_='foreignkey')
    op.create_foreign_key(None, 'Characters', 'Planets', ['homeworld'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Favorite Characters_ibfk_2', 'Favorite Characters', type_='foreignkey')
    op.drop_constraint('Favorite Characters_ibfk_1', 'Favorite Characters', type_='foreignkey')
    op.create_foreign_key(None, 'Favorite Characters', 'User', ['User_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Favorite Characters', 'Characters', ['Characters_Relation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Favorite Planets_ibfk_2', 'Favorite Planets', type_='foreignkey')
    op.drop_constraint('Favorite Planets_ibfk_1', 'Favorite Planets', type_='foreignkey')
    op.create_foreign_key(None, 'Favorite Planets', 'User', ['User_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Favorite Planets', 'Planets', ['Planets_Relation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Favorite Starships_ibfk_1', 'Favorite Starships', type_='foreignkey')
    op.drop_constraint('Favorite Starships_ibfk_2', 'Favorite Starships', type_='foreignkey')
    op.create_foreign_key(None, 'Favorite Starships', 'User', ['User_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Favorite Starships', 'Starships', ['Starships_Relation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Pilots_ibfk_2', 'Pilots', type_='foreignkey')
    op.drop_constraint('Pilots_ibfk_1', 'Pilots', type_='foreignkey')
    op.create_foreign_key(None, 'Pilots', 'Characters', ['Characters_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Pilots', 'Starships', ['Starships_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Starships_ibfk_1', 'Starships', type_='foreignkey')
    op.create_foreign_key(None, 'Starships', 'Characters', ['pilot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Starships', type_='foreignkey')
    op.create_foreign_key('Starships_ibfk_1', 'Starships', 'Characters', ['pilot_id'], ['id'])
    op.drop_constraint(None, 'Pilots', type_='foreignkey')
    op.drop_constraint(None, 'Pilots', type_='foreignkey')
    op.create_foreign_key('Pilots_ibfk_1', 'Pilots', 'Characters', ['Characters_id'], ['id'])
    op.create_foreign_key('Pilots_ibfk_2', 'Pilots', 'Starships', ['Starships_id'], ['id'])
    op.drop_constraint(None, 'Favorite Starships', type_='foreignkey')
    op.drop_constraint(None, 'Favorite Starships', type_='foreignkey')
    op.create_foreign_key('Favorite Starships_ibfk_2', 'Favorite Starships', 'User', ['User_id'], ['id'])
    op.create_foreign_key('Favorite Starships_ibfk_1', 'Favorite Starships', 'Starships', ['Starships_Relation_id'], ['id'])
    op.drop_constraint(None, 'Favorite Planets', type_='foreignkey')
    op.drop_constraint(None, 'Favorite Planets', type_='foreignkey')
    op.create_foreign_key('Favorite Planets_ibfk_1', 'Favorite Planets', 'Planets', ['Planets_Relation_id'], ['id'])
    op.create_foreign_key('Favorite Planets_ibfk_2', 'Favorite Planets', 'User', ['User_id'], ['id'])
    op.drop_constraint(None, 'Favorite Characters', type_='foreignkey')
    op.drop_constraint(None, 'Favorite Characters', type_='foreignkey')
    op.create_foreign_key('Favorite Characters_ibfk_1', 'Favorite Characters', 'Characters', ['Characters_Relation_id'], ['id'])
    op.create_foreign_key('Favorite Characters_ibfk_2', 'Favorite Characters', 'User', ['User_id'], ['id'])
    op.drop_constraint(None, 'Characters', type_='foreignkey')
    op.create_foreign_key('Characters_ibfk_1', 'Characters', 'Planets', ['homeworld'], ['id'])
    # ### end Alembic commands ###
